### ISSUE TITLE
help for write one test case with one of the elgg module

### ISSUE THREAD

**Issue by dipenpatel235** [stianlik/elgg-phpunit#1]
hello..
i am looking for help to choose any of elgg module and write one sample test case with elgg 2.3

beucase not gettig idea after did by
composer require foogile/elgg-phpunit

Thanks

**Comment by stianlik** [comment]
I haven't used Elgg in years, so this could be a bit outdated. I suggest taking a look at [the testing section in official documentation](http://learn.elgg.org/en/latest/contribute/tests.html) before you start. All you need to do to test a plugin is to write a [PHPUnit](https://phpunit.de/) test case. To use this plugin, place the files in the following directories:

- `PLUGIN/src/`: Your code
- `PLUGIN/tests/`: Your tests
- `PLUGIN/tests/unit/`: Unit tests (no integration with Elgg required)
- `PLUGIN/tests/integration/`: Integration tests (Elgg API available)

Start with a simple unit test, and move on to integration testing when you're comfortable with PHPUnit.
